# Generated by Django 3.1.2 on 2020-10-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClonerService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='cookie',
            field=models.BinaryField(default=b'NONE'),
        ),
    ]
